### ISSUE TITLE
Adding variables to constructor not necessary

### ISSUE THREAD

**Issue by csllvn33** [csalva0604/Salva_CSCI2270_FinalProject#1]
Hi, just would like to say that initializing variables in your constructor isn't necessary because you do not have private variables in your class. I could be wrong but I strongly believe this is the case and your code runs fine!

**Comment by ghost** [comment]
If the user enters invalid input, such as strings, characters or an int not assigned to a gymnast, the program still runs but outputs invalid results. Checking that the user input is valid before printing any results could resolve this issue. Otherwise the code runs fine!

**Comment by csalva0604** [comment]
Thank you to both of you!
